# Generated by Django 2.1.12 on 2020-01-24 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('edad', models.PositiveIntegerField()),
                ('direccion', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'db_personal',
            },
        ),
    ]
